# -*- coding: utf-8 -*-
"""11 file_handeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYI781-HpD4OMfeoNBDvKYPvcxy28BgO
"""

from google.colab import files
uploaded = files.upload()

filename = "1test.txt"

file = open(filename)
cont = file.read()
print(cont)

f = open(filename, "w")
f.write("hello world")
f.close()

f = open(filename, "a")
f.write("\nThis is added text.")
f.close()

f = open(filename, "r+")
print(f.read())
f.write("hello world")
f.close()

f = open(filename, "w+")
f.write("hello world")
f.seek(0)
print(f.read())
f.close()

f = open(filename, "a+")
f.write("hello world")
f.seek(0)
print(f.read())
f.close()


f = open(filename, "r")
f.close()


with open(filename , 'w+') as f2:
  cont = input("enter to write = ")
  f2.write(cont)
  f2.seek(0)
  print(f2.read())


import os
if os.path.exists(filename ):
  print("The file exist")
else:
  print("The file does not exist")